#!/usr/bin/env bash
# generate-index.sh - Auto-generate COMMANDS.md index from frontmatter
# Scans commands/ and creates categorized command list

set -euo pipefail
set -x

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

OUTPUT_FILE="COMMANDS.md"

# Extract frontmatter field
extract_field() {
    local file="$1"
    local field="$2"

    awk -v field="$field" '
        /^---$/ { if (++count == 2) exit }
        count == 1 && $0 ~ "^" field ":" {
            sub("^" field ": *", "")
            print
        }
    ' "$file"
}

# Generate index
generate_index() {
    local temp_file
    temp_file=$(mktemp)

    cat > "$temp_file" <<'EOF'
# Commands Index

This file is auto-generated from command frontmatter. Do not edit manually.

## Available Commands

EOF

    # Collect commands using temp file (compatible with older bash)
    local temp_data
    temp_data=$(mktemp)
    trap "rm -f $temp_data" EXIT

    while IFS= read -r -d '' file; do
        local name description argument_hint
        name=$(extract_field "$file" "name")
        description=$(extract_field "$file" "description")
        argument_hint=$(extract_field "$file" "argument-hint")

        if [[ -n "$name" ]]; then
            # Determine category from file path or name
            local category="General"
            if [[ "$file" =~ obsidian-workflows ]]; then
                category="Obsidian-Workflows"
            elif [[ "$file" =~ obsidian:write ]]; then
                category="Obsidian-Write"
            fi

            # Store command data: category|name|file|description|argument_hint
            echo "${category}|${name}|${file}|${description}|${argument_hint}" >> "$temp_data"
        fi
    done < <(find commands -type f -name "*.md" -print0 | sort -z)

    # Get unique categories
    local categories
    categories=$(cut -d'|' -f1 "$temp_data" | sort -u)

    # Output by category
    for category in $categories; do
        # Convert category name back to readable format
        local display_category="${category//-/ }"
        echo "" >> "$temp_file"
        echo "### $display_category" >> "$temp_file"
        echo "" >> "$temp_file"

        # Output commands in this category
        while IFS='|' read -r cat name file description argument_hint; do
            if [[ "$cat" == "$category" ]]; then
                local display_name="$name"
                if [[ "$cat" == "Obsidian-Workflows" && "$name" != *:* ]]; then
                    display_name="obsidian-workflows:${name}"
                fi

                echo "#### \`/$display_name\`" >> "$temp_file"
                echo "" >> "$temp_file"
                echo "$description" >> "$temp_file"
                echo "" >> "$temp_file"
                if [[ -n "$argument_hint" ]]; then
                    echo "**Usage:** \`$argument_hint\`" >> "$temp_file"
                    echo "" >> "$temp_file"
                fi
                echo "**Source:** [\`$file\`]($file)" >> "$temp_file"
                echo "" >> "$temp_file"
            fi
        done < <(sort -t'|' -k2 "$temp_data")
    done

    # Add footer
    cat >> "$temp_file" <<'EOF'

---

*Generated by `tools/generate-index.sh`*
EOF

    # Move to final location
    mv "$temp_file" "$OUTPUT_FILE"
    echo -e "${GREEN}Generated $OUTPUT_FILE${NC}"
}

# Main execution
main() {
    if [[ ! -d "commands" ]]; then
        echo -e "${YELLOW}WARNING${NC}: commands directory not found"
        exit 1
    fi

    generate_index
}

main "$@"
